FROM nginx:stable-perl

RUN apt update
RUN apt install -y procps
RUN apt install -y openssl
RUN mkdir -p /etc/nginx/certs/self-signed/
RUN openssl req -x509 -nodes -days 365000 -newkey rsa:2048 -keyout /etc/nginx/certs/self-signed/ssldocker.test.key -out /etc/nginx/certs/self-signed/ssldocker.test.crt -subj "/C=US/ST=California/L=San Francisco/O=My Company/CN=ssldocker.test"
RUN openssl dhparam -out /etc/nginx/certs/dhparam.pem 2048

COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf

CMD [ "nginx", "-g", "daemon off;" ]
