services:
    web:
        build:
            context: .
            dockerfile: Dockerfile_4_nginx
        container_name: nginx_https

        ports:
            - '80:80'
            - '443:443'

        volumes:
            - ./src:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php-fpm

    php-fpm:
        build: 
            context: .
            dockerfile: Dockerfile_4_php

        container_name: php-fpm
        volumes:
            - ./src:/var/www/html

    db:
        image: percona:ps-8.0.41-32
        container_name: percona_db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: example
